name: Track changes to AWS Service Terms and Customer Agreement

on:
  schedule:
    - cron: "54 15 * * *"

jobs:
  Download-Terms:
    runs-on: ubuntu-latest
    steps:

      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install python3-html2text
      - run: curl https://aws.amazon.com/service-terms/ -o terms.html
      - run: curl https://aws.amazon.com/agreement/ -o agreement.html
      - run: html2markdown terms.html > terms.md
      - run: html2markdown agreement.html > agreement.md
      - run: csplit terms.md '/AWS Service Terms/'
      - run: csplit xx01 '/Previous version/' --suppress-matched
      - run: mv xx00 service-terms.md
      - run: rm -f xx01 terms.html terms.md
      - run: csplit agreement.md '/AWS Customer Agreement/'
      - run: csplit xx01 '/Prior Version/' --suppress-matched
      - run: mv xx00 customer-agreement.md
      - run: rm -f xx01 agreement.html agreement.md
      - name: Create report file
        run: date +%s > last-checked.txt
      - name: Commit report
        run: |
          git config --global user.name 'Thomas Lund'
          git config --global user.email 'thlund@users.noreply.github.com'
          git add last-checked.txt
          git add service-terms.md
          git commit -am "Automated check"
          git push
